server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myproject?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: dnjswns98!
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.dashboard.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.dashboard.mapper: DEBUG
    org.springframework.web: DEBUG

# JWT 설정
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 1800000  # 30분 (밀리초)

bank-of-korea:
  api-key: G3LFGSOI6YMDYPGJXG42