name: Backend CI/CD

on:
  push:
    branches: [ "master" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: m2-${{ runner.os }}-

      - name: Build with Maven
        run: mvn -B -ntp -f backend/pom.xml package


      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "backend/target/*.jar"
          target: "/home/ec2-user/app/"
          strip_components: 2
          overwrite: true
          args: "-o StrictHostKeyChecking=no"

      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          args: "-o StrictHostKeyChecking=no"
          script: |
            set -e
            cd /home/ec2-user/app
            
            # 최신 jar를 app.jar로 이름 변경
            LATEST_JAR=$(ls -t *.jar | head -n 1)
            cp "$LATEST_JAR" app.jar
            
            # 백엔드 서비스 재시작
            sudo systemctl restart dashboard-backend
            
            # 헬스체크 (최대 20초 대기)
            for i in {1..20}; do
              sleep 1
              if curl -sSf http://127.0.0.1:8080/actuator/health >/dev/null 2>&1; then
                echo "✅ Backend health check passed"
                exit 0
              fi
            done
            
            echo "❌ Backend health check failed"
            sudo journalctl -u dashboard-backend --no-pager -n 50
            exit 1
