name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy to EC2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # 빌드 파일 업로드
          scp -i private_key.pem -o StrictHostKeyChecking=no -r frontend/build/* $SSH_USER@$SSH_HOST:/home/ec2-user/frontend/build/

          # EC2에서 배포 스크립트 실행
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "bash ~/deploy/frontend/deploy.sh"
